### PR TITLE
[PR] New layout for The Evidence

### PR DESCRIPTION
**Pull request by jeremyfelt**

### CODE REVIEW

**Comment by philcable** [comment]
@jeremyfelt @slocker3 Please take a look at this when you get a chance! If it looks like it'll work for the desktop view, I'll tidy it up, then put styles in place for mobile views.

**Comment by philcable** [comment]
These two commits make for a more complete experience.

**Comment by philcable** [comment]
@allenjohns and I made a few style revisions late this morning, so those are included here.

@jeremyfelt #reviewmerge?

**Comment by jeremyfelt** [comment]
Looking excellent. Merging as soon as this next Travis run passes.

**Pull request merged**
