### PR TITLE
[PR] Don't set static width and heigh attributes on images

### PR DESCRIPTION
**Pull request by jeremyfelt**
This allows us to better target the image sizes with CSS.

### CODE REVIEW

**Comment by jeremyfelt** [comment]
@philcable #reviewmerge?

**Comment by jeremyfelt** [comment]
Pause review 😄 

I'm going to add an attribute/field for class name on the images.

**Comment by philcable** [comment]
Looks good!

**Comment by jeremyfelt** [comment]
Never mind on the pause, I just missed it. New branch! :)

**Pull request merged**
